title: Johnsey Wedding
email: wedding@johnsey.me
description: >- 
  Jena and Michael Johnsey's wedding website.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://wedding.johnsey.me" # the base hostname & protocol for your site, e.g. http://example.com
github_username: mjohnsey

# Build settings
markdown: kramdown
theme: minima

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - legacy-site/
  - README.md
